/**
 * @deprecated Preferir `app/modules/orcamentos` — reexport de compatibilidade.
 */
export type {
  EquipamentoArmazemRef,
  EquipamentoClienteRef,
  PedidoOrcamentoRef,
  PedidoAvulsoRef,
  OrcamentoGeradoRef,
} from '../modules/orcamentos/equipamento'
export {
  resolverChaveEquipamentoCliente,
  equipamentoCorrespondeChave,
  pedidoRelatorioCorrespondeEquipamento,
  pedidoAvulsoCorrespondeEquipamento,
  orcamentoGeradoCorrespondeEquipamento,
  orcamentoStatusParaPedidoRelatorio,
  findOrcamentoGeradoParaPedidoRelatorio,
  findOrcamentoGeradoParaPedidoAvulso,
  statusEfetivoPedidoAvulso,
  pedidoAvulsoCancelado,
  orcamentoGeradoCancelado,
  pedidoRelatorioCancelado,
  statusEfetivoPedidoRelatorio,
  pedidoRelatorioPendenteComOrcamento,
  pedidoRelatorioAprovadoComOrcamento,
  dedupePedidosRelatorioCliente,
  chaveOrcamentoRelatorioJaTemPedido,
  aprovarPedidosOrcamentoRelatorio,
  aprovarOrcamentosGeradosRelatorio,
  aplicarPatchPedidoFromOrcamentoGerado,
  pedidoRelatorioPendente,
  pedidoRelatorioAprovado,
  pedidoAvulsoPendente,
  pedidoAvulsoAprovado,
  orcamentoGeradoPendente,
  orcamentoGeradoAprovado,
  pedidoAvulsoEntregaAguardandoNotaFiscal,
  orcamentoEntregaAguardandoNotaFiscal,
  pedidoAvulsoAprovadoSemEntrega,
  orcamentoGeradoAprovadoSemEntrega,
  clienteCorrespondeRegistro,
  pedidoRelatorioCorrespondeCliente,
  pedidoAvulsoCorrespondeCliente,
  orcamentoGeradoCorrespondeCliente,
  rotuloEquipamentoPedidoRelatorio,
  rotuloEquipamentoPedidoAvulso,
  rotuloEquipamentoOrcamentoGerado,
  mergeOrcamentosGeradosArrays,
  enrichOrcamentosGeradosComPedidosAvulsos,
} from '../modules/orcamentos/equipamento'
export { gerarProximoCodigoPedidoRelatorio } from './orcamentosNumero'
