/**
 * @deprecated Preferir `app/modules/relatorios-especiais` — reexport de compatibilidade.
 */
export type {
  TotaisRelatorioEspecial,
  DiaSemanaLabels,
  SessaoHorasEquipamentoEspecial,
  ResumoHorasTrabalhoDia,
  DiaSemMaquinaResumoEspecial,
  EquipamentoRefMinEspecial,
  ColetarDiasSemMaquinaOpts,
  DistribuicaoAlmocoLinhas,
} from '../modules/relatorios-especiais/calculos'
export {
  calcularDuracaoHoras,
  minutosDeDuracaoHHMM,
  minutosPausaOuAlmocoDia,
  minutosViagemDia,
  minutosAlmocoDia,
  minutosTrabalhoBrutoDia,
  minutosTrabalhoLiquidoDia,
  indiceLinhaAlmocoActiva,
  distribuirAlmocoPorLinhaEquipamentoDia,
  minutosLiquidosPorLinhaEquipamentoDia,
  formatMinutosComoHHMM,
  horasEquipamentoDiaBruto,
  atualizarHorasEquipamentoDia,
  atualizarCalculosDiaEspecial,
  diaContaComoDiariaEspecial,
  calcularTotaisRelatorioEspecial,
  aplicarTotaisNoRelatorioEspecial,
  diaTrabalhoDataChaveOrdenacao,
  getDiaSemanaInfo,
  formatDiaComDiaSemana,
  sortDiasTrabalhoEspecialCronologicamente,
  formatDiaCurtoPt,
  intervaloHorasTrabalhoDia,
  intervaloViagemDia,
  resumoHorasTrabalhoDia,
  contarEquipamentosUnicosDia,
  equipamentosContextoDiaEspecial,
  coletarDiasSemMaquinaResumo,
  coletarSessoesPorEquipamento,
} from '../modules/relatorios-especiais/calculos'
