import type { SidebarGroup } from './tipos'

export const SIDEBAR_GROUPS: SidebarGroup[] = [
  'gestao-tecnica',
  'parceiros-comercial',
  'documentacao-relatorios',
  'pecas-biblioteca',
  'gestao-custos',
  'checklist-group',
  'gestao-industrial',
  'comunicacao-interna',
  'manuais-informacoes-tecnicas',
  'biblia-nonato-service',
  'almoxarifado-armazem',
  'gestao-financeira',
  'empresa-institucional',
  'outros',
]

export const SIDEBAR_GROUP_LAUNCHER_IDS = new Set([
  'gestao-tecnica-default',
  'parceiros-comercial-default',
  'documentacao-relatorios-default',
  'pecas-biblioteca-default',
  'gestao-custos-default',
  'gestao-industrial-default',
  'gestao-financeira-default',
  'administrador-default',
  'extras-default',
])

export const SIDEBAR_PINNED_IDS = new Set([
  'cadastro-nonato-service-default',
  'ficha-pagamento-transferencia-default',
  'ficha-fatura-cliente-default',
])

/** Separadores que pertencem ao bloco «Gestão financeira» na sidebar. */
export const GESTAO_FINANCEIRA_TAB_TYPES = new Set<string>([
  'gestao-financeira',
  'clientes-financeiro',
  'comprovantes-despesas',
  'registro-despesas',
  'pagamentos-contador',
  'orcamentos-avulso',
  'pedido-orcamentos-avulso',
  'orcamentos-pecas-especiais',
  'orcamento-servico-tecnico',
])

export const SIDEBAR_TRANSLATION_KEY_BY_ID: Record<string, string> = {
  'extras-default': 'administrador',
  'cadastro-nonato-service-default': 'cadastroNonatoServiceTitle',
  'ficha-pagamento-transferencia-default': 'fichaPagamentoTransferenciaTitle',
  'ficha-fatura-cliente-default': 'fichaFaturaClienteTitle',
  'gestores-default': 'gestoresTitle',
  'familias-grupos-default': 'familiasGruposTitle',
  'familias-grupos-equipamentos-default': 'familiasGruposEquipamentosTitle',
  'equipamentos-default': 'equipamentosTitle',
  'checklist-group-default': 'checklistGroupTitle',
  'pre-checklist-default': 'preChecklistSubTitle',
  'checklist-basico-default': 'checklistBasicoSubTitle',
  'checklist-default': 'checklistSubTitle',
  'verificacao-final-entrega-default': 'verificacaoFinalEntregaTitle',
  'clientes-default': 'clientesTitle',
  'fornecedores-default': 'fornecedoresTitle',
  'relatorio-servico-default': 'relatorioServicoTitle',
  'relatorio-especial-default': 'relatorioEspecialTitle',
  'biblioteca-pecas-default': 'cadastroPecasBibliotecaTitle',
  'solicitacao-servico-tecnico-default': 'solicitacaoServicoTecnicoTitle',
  'agenda-default': 'agendaTitle',
  'diario-pedidos-dia-default': 'diarioPedidosTitle',
  'estado-visual-tecnico-default': 'estadoVisualTecnico',
  'informacoes-conhecimento-tecnicos-default': 'informacoesConhecimentoTecnicosTitle',
  'biblioteca-relatorios-default': 'bibliotecaRelatoriosTitle',
  'relatorios-excluidos-clientes-default': 'relatoriosExcluidosClientesTitle',
  'cadastro-servicos-default': 'cadastroServicosTitle',
  'fechamento-relatorios-servicos-default': 'fechamentoRelatoriosServicosTitle',
  'orcamentos-avulso-default': 'orcamentosAvulsoTitle',
  'orcamento-servico-tecnico-default': 'orcamentoServicoTecnicoTitle',
  'orcamentos-pecas-especiais-default': 'orcamentoPecasEspeciaisTitle',
  'pedido-orcamentos-avulso-default': 'pedidoOrcamentosAvulsoTitle',
  'registro-despesas-default': 'registroDespesasTitle',
  'mapa-visual-separacao-pecas-default': 'mapaVisualSeparacaoPecasTitle',
  'desmontados-default': 'desmontadosTitle',
  'manuais-informacoes-tecnicas-default': 'manuaisInformacoesTecnicasTitle',
  'biblia-nonato-service-default': 'bibliaNonatoServiceTitle',
  'almoxarifado-armazem-default': 'almoxarifadoArmazemTitle',
  'gestao-tecnica-default': 'gestaoTecnicaTitle',
  'parceiros-comercial-default': 'parceirosComercialTitle',
  'documentacao-relatorios-default': 'documentacaoRelatoriosTitle',
  'pecas-biblioteca-default': 'pecasBibliotecaTitle',
  'gestao-industrial-default': 'gestaoIndustrialTitle',
  'gestao-financeira-default': 'gestaoFinanceiraTitle',
  'gestao-custos-default': 'gestaoCustosTitle',
  'comunicacao-interna-default': 'comunicacaoInternaTitle',
  'hub-comunicacao-default': 'hubComunicacao',
  'mensagens-internas-default': 'mensagensInternas',
  'mensagens-internas-tecnicos-default': 'mensagensInternasTecnicos',
  'tecnicos-internos-default': 'tecnicosInternos',
  'tecnicos-externos-default': 'tecnicosExternos',
  'alerta-mensagens-default': 'alertaMensagens',
  'clientes-financeiro-default': 'clientesFinanceiroTitle',
  'comprovantes-despesas-default': 'comprovantesDespesasTitle',
  'pagamentos-contador-default': 'pagamentosContadorTitle',
  'administrador-default': 'administrador',
}

export const SIDEBAR_SECTION_ICONS: Record<string, string> = {
  operacao: '🔧',
  comercial: '💼',
  documentacao: '📋',
  comunicacao: '💬',
  industrial: '🏭',
  checklist: '✅',
  'pecas-armazem': '📦',
  institucional: '🏛️',
  sistema: '⚙️',
}
