/** Ícones da barra lateral — figura curta por acção (reconhecimento rápido). */

export const SIDEBAR_ACTION_GLYPHS: Record<string, string> = {
  'open-clientes': '👤',
  'open-fornecedores': '🏭',
  'open-gestores': '👷',
  'open-cadastro-servicos': '💶',
  'open-agenda': '📅',
  'open-diario-pedidos-dia': '📓',
  'open-estado-visual-tecnico': '📍',
  'open-informacoes-conhecimento-tecnicos': '🧠',
  'open-relatorio-servico': '📝',
  'open-relatorio-especial': '📊',
  'open-biblioteca-relatorios': '📚',
  'open-relatorios-excluidos-clientes': '🗃️',
  'open-fechamento-relatorios-servicos': '✅',
  'open-biblioteca-pecas': '🧩',
  'open-cadastro-pecas-stock': '📦',
  'open-orcamentos-avulso': '💼',
  'open-pedido-orcamentos-avulso': '📨',
  'open-orcamentos-pecas-especiais': '🔧',
  'open-orcamento-servico-tecnico': '🛠️',
  'open-clientes-financeiro': '💳',
  'open-comprovantes-despesas': '🧾',
  'open-registro-despesas': '📒',
  'open-pagamentos-contador': '🏦',
  'open-equipamentos': '🖥️',
  'open-familias-grupos-equipamentos': '🌳',
  'open-desmontados': '⚙️',
  'open-pre-checklist': '☑️',
  'open-checklist-basico': '📋',
  'open-checklist': '✅',
  'open-gestao-grupos-checklist': '📁',
  'open-ordem-preparacao': '📨',
  'open-formularios-checklist-tecnicos': '📄',
  'open-verificacao-final-entrega': '🏁',
  'open-familias-grupos': '🏷️',
  'open-hub-comunicacao': '💬',
  'open-mensagens-internas': '✉️',
  'open-mensagens-internas-tecnicos': '📡',
  'open-alerta-mensagens': '🔔',
  'open-manuais-informacoes-tecnicas': '📖',
  'open-biblia-nonato-service': '✝️',
  'open-almoxarifado-armazem': '🏬',
  'open-mapa-visual-separacao-pecas': '🗺️',
  'open-cadastro-nonato-service': '🏛️',
  'open-ficha-pagamento-transferencia': '💸',
  'open-ficha-fatura-cliente': '📑',
  'open-solicitacao-servico-tecnico': '🎫',
  'open-protocolos-servico': '📜',
  'open-manual-programa': '📘',
  'open-administrador': '⚙️',
  'open-gestao-tecnica': '🔧',
  'open-parceiros-comercial': '🗂️',
  'open-gestao-custos': '💵',
  'open-gestao-financeira': '💹',
  'open-documentacao-relatorios': '📋',
  'open-pecas-biblioteca': '📦',
  'open-comunicacao-interna': '💬',
  'open-checklist-group': '✅',
}

export function getSidebarActionGlyph(action: string, fallback = '▸'): string {
  const key = String(action || '').trim()
  return SIDEBAR_ACTION_GLYPHS[key] || fallback
}
