/**
 * Formatos visuais para impressão PDF dos Protocolos de Serviço (HTML → Imprimir / Guardar como PDF).
 * A4, tipografia e espaçamento pensados para documento profissional.
 */

export const PROTOCOLO_SERVICO_PDF_MODELOS_MAX = 12

export function clampProtocoloPdfModelo(n: number | undefined): number {
  return Math.min(PROTOCOLO_SERVICO_PDF_MODELOS_MAX, Math.max(1, Number(n) || 1))
}

type HeaderOpts = {
  tituloProto: string
  dataDoc: string
  logoHtml: string
}

const PRINT_SAFE = `@page{size:A4;margin:11mm}@media print{body{-webkit-print-color-adjust:exact;print-color-adjust:exact;}}`

function logoOrName(logoHtml: string): string {
  return logoHtml || '<span class="logo-fallback">NONATO SERVICE</span>'
}

function escAttr(s: string): string {
  return String(s || '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

/** Estilos de blocos de texto / fluxo do corpo (índice 0–11) */
export const PROTOCOLO_PDF_BLOCO_STYLES: string[] = [
  'margin:14px 0;padding:15px 18px;background:#f8fafc;border-radius:11px;border:1px solid #e2e8f0;box-shadow:0 1px 2px rgba(15,23,42,0.04);color:#334155;font-size:11.5pt;line-height:1.5;',
  'margin:14px 0;padding:14px 16px;background:linear-gradient(180deg,#f8fafc 0%,#f1f5f9 100%);border-radius:8px;border-left:4px solid #2563eb;box-shadow:inset 0 1px 0 rgba(255,255,255,0.8);color:#0f172a;font-size:11.5pt;line-height:1.5;',
  'margin:14px 0;padding:15px 17px;background:#fff;border-radius:10px;border:1px solid #cbd5e1;box-shadow:0 2px 8px rgba(15,23,42,0.06);color:#1e293b;font-size:11.5pt;line-height:1.5;',
  'margin:14px 0;padding:16px 18px;background:#fff;border-radius:14px;border:1px solid #ccfbf1;box-shadow:0 4px 16px rgba(13,148,136,0.1);color:#134e4a;font-size:11.5pt;line-height:1.45;',
  'margin:14px 0;padding:12px 14px;background:#fafafa;border:1px dashed #64748b;border-radius:4px;font-family:Consolas,ui-monospace,monospace;font-size:10.5pt;line-height:1.55;color:#111827;',
  'margin:14px 0;padding:16px 18px;background:linear-gradient(180deg,#fffbeb 0%,#fff7ed 100%);border-radius:6px;border:1px solid #e7d5c4;font-family:Georgia,ui-serif,serif;font-size:11.5pt;line-height:1.55;color:#422006;',
  'margin:14px 0;padding:15px 18px;background:#f8fafc;border-radius:8px;border-left:5px solid #475569;color:#334155;font-size:11.5pt;line-height:1.5;',
  'margin:14px 0;padding:16px 20px;background:#fff;border:2px solid #1e293b;border-radius:2px;color:#0f172a;font-size:11.5pt;line-height:1.55;',
  'margin:14px 0;padding:15px 18px;background:#eff6ff;border-radius:12px;border:1px solid #bfdbfe;color:#1e3a5f;font-size:11.5pt;line-height:1.5;',
  'margin:14px 0;padding:16px 18px;background:linear-gradient(135deg,#18181b 0%,#27272a 100%);border-radius:10px;border:1px solid #3f3f46;color:#fafafa;font-size:11.5pt;line-height:1.5;',
  'margin:14px 0;padding:14px 17px;background:#fff;border-radius:8px;border-left:6px solid #4f46e5;box-shadow:0 2px 10px rgba(79,70,229,0.08);color:#1e1b4b;font-size:11.5pt;line-height:1.5;',
  'margin:14px 0;padding:13px 15px;background:#f9fafb;border:1px solid #d1d5db;border-radius:2px;font-family:ui-monospace,Consolas,monospace;font-size:10.5pt;line-height:1.55;color:#111827;',
]

/** Raio das imagens antes/depois */
export const PROTOCOLO_PDF_IMG_RADIUS: number[] = [10, 8, 10, 14, 5, 7, 9, 3, 12, 8, 10, 4]

function buildHeaderFragments(o: HeaderOpts): string[] {
  const { tituloProto, dataDoc, logoHtml } = o
  const t = escAttr(tituloProto)
  const d = escAttr(dataDoc)
  const L = logoOrName(logoHtml)
  const Lraw = logoHtml || '<span style="font-size:17px;font-weight:800;color:#1e40af;letter-spacing:0.02em;">NONATO SERVICE</span>'
  return [
    `<div class="pdf-header m1"><div class="pdf-header-inner"><div class="pdf-header-logo">${L}</div><div class="pdf-header-text"><div class="pdf-header-kicker">NONATO SERVICE</div><div class="pdf-header-doc">${t}</div><div class="pdf-header-meta">${d}</div></div></div><div class="pdf-header-line"></div></div>`,
    `<div class="pdf-header m2"><div class="m2-inner"><div class="m2-left">${logoHtml ? `<div class="m2-logo">${logoHtml}</div>` : ''}<div class="m2-kicker">NONATO SERVICE</div></div><div class="m2-right"><div class="m2-title">${t}</div><div class="m2-sub">Documento de intervenção técnica</div><div class="m2-date">${d}</div></div></div></div>`,
    `<div class="pdf-header m3"><div class="m3-bar"></div><div class="m3-inner"><div class="m3-left">${logoHtml || ''}<div class="m3-brand">NONATO SERVICE</div></div><div class="m3-right"><div class="m3-title">${t}</div><div class="m3-date">${d}</div></div></div></div>`,
    `<div class="pdf-header m4"><div class="m4-accent"></div><div class="m4-inner"><div class="m4-logo">${L}</div><div class="m4-text"><div class="m4-company">NONATO SERVICE</div><div class="m4-doc">${t}</div><div class="m4-date">${d}</div></div></div></div>`,
    `<div class="pdf-header m5"><div class="m5-strip">PROTOCOLO DE SERVIÇO · DOCUMENTO TÉCNICO</div><div class="m5-body"><span class="m5-logo">${logoHtml || '<span class="m5-fallback">NONATO SERVICE</span>'}</span><span class="m5-meta"><strong>${t}</strong><br/><span class="m5-d">${d}</span></span></div></div>`,
    `<div class="pdf-header m6"><div class="m6-gold"></div><div class="m6-inner"><div class="m6-title">NONATO SERVICE</div><div class="m6-sub">${t}</div><div class="m6-row">${logoHtml ? `<span class="m6-logo">${logoHtml}</span>` : ''}<span class="m6-date">${d}</span></div></div></div>`,
    `<div class="pdf-header m7"><div class="m7-inner"><div class="m7-logo">${Lraw}</div><div class="m7-main"><div class="m7-brand">NONATO SERVICE</div><h1 class="m7-doc">${t}</h1><div class="m7-foot"><span>${d}</span></div></div></div></div>`,
    `<div class="pdf-header m8"><div class="m8-frame"><div class="m8-logo">${L}</div><div class="m8-center"><div class="m8-name">NONATO SERVICE</div><div class="m8-doc">${t}</div><div class="m8-date">${d}</div></div></div></div>`,
    `<div class="pdf-header m9"><div class="m9-inner"><div class="m9-badge"></div><div class="m9-content"><div class="m9-logo">${logoHtml || ''}</div><div><div class="m9-brand">NONATO SERVICE</div><div class="m9-title">${t}</div><div class="m9-date">${d}</div></div></div></div></div>`,
    `<div class="pdf-header m10"><div class="m10-gold"></div><div class="m10-inner"><div class="m10-left">${L}</div><div class="m10-right"><div class="m10-k">NONATO SERVICE</div><div class="m10-t">${t}</div><div class="m10-d">${d}</div></div></div></div>`,
    `<div class="pdf-header m11"><div class="m11-stripe"></div><div class="m11-inner"><div class="m11-logo">${L}</div><div class="m11-text"><div class="m11-b">NONATO SERVICE</div><div class="m11-d">${t}</div><div class="m11-meta">${d}</div></div></div></div>`,
    `<div class="pdf-header m12"><div class="m12-top">RELATÓRIO TÉCNICO / PROTOCOLO DE SERVIÇO</div><div class="m12-mid"><span class="m12-logo">${logoHtml || 'NONATO SERVICE'}</span><span class="m12-info">${t} · <strong>${d}</strong></span></div><div class="m12-rule"></div></div>`,
  ]
}

function cssBlocks(): string[] {
  return [
    PRINT_SAFE +
      `body{font-family:'Segoe UI',system-ui,-apple-system,sans-serif;margin:0;padding:0;color:#1e293b;font-size:11.5pt;line-height:1.45;background:#fff;}.pdf-header.m1{background:linear-gradient(165deg,#0c4a0e 0%,#052e05 100%);color:#fff;padding:0;}.pdf-header-inner{display:flex;align-items:flex-start;justify-content:space-between;gap:20px;padding:24px 28px;flex-wrap:wrap;}.pdf-header-logo img{max-height:56px;max-width:200px;object-fit:contain;}.logo-fallback{font-size:22px;font-weight:800;color:#86efac;letter-spacing:0.04em;}.pdf-header-kicker{font-size:10px;font-weight:700;letter-spacing:0.2em;color:#86efac;opacity:0.95;margin-bottom:6px;}.pdf-header-doc{font-size:15px;font-weight:600;color:#fff;max-width:420px;line-height:1.35;}.pdf-header-meta{font-size:10px;color:#bbf7d0;margin-top:10px;opacity:0.9;}.pdf-header-line{height:4px;background:linear-gradient(90deg,#16a34a,#4ade80,#16a34a);}.body-wrap{padding:8px 4px 28px;}.sec{margin:18px 0;padding:18px 22px;background:#fff;border:1px solid #e2e8f0;border-radius:12px;box-shadow:0 2px 8px rgba(15,23,42,0.04);}.sec-title{margin:0 0 14px;font-size:10.5px;font-weight:800;letter-spacing:0.1em;color:#15803d;text-transform:uppercase;padding-bottom:10px;border-bottom:2px solid #bbf7d0;}.cl-table{width:100%;border-collapse:collapse;}.cl-table tr:not(:last-child){border-bottom:1px solid #f1f5f9;}.cl-table .cl-label{width:34%;padding:10px 14px 10px 0;vertical-align:top;font-weight:700;color:#64748b;font-size:9.5px;text-transform:uppercase;letter-spacing:0.06em;}.cl-table .cl-value{padding:10px 0;color:#0f172a;font-size:11pt;}.texto-inicial{white-space:pre-wrap;margin:0;color:#334155;line-height:1.55;}.footer-bar{margin-top:26px;padding-top:16px;border-top:1px solid #e2e8f0;display:flex;justify-content:space-between;align-items:flex-end;flex-wrap:wrap;gap:12px;}.footer-date{font-size:10px;color:#64748b;}.doc-ref{font-size:8.5px;color:#94a3b8;font-family:Consolas,ui-monospace,monospace;letter-spacing:0.02em;}`,
    PRINT_SAFE +
      `body{font-family:'Segoe UI',system-ui,sans-serif;margin:0;padding:0;color:#0f172a;font-size:11.5pt;background:#f8fafc;}.pdf-header.m2{background:#fff;border-bottom:1px solid #e2e8f0;}.m2-inner{display:flex;justify-content:space-between;align-items:flex-start;gap:24px;padding:22px 28px;flex-wrap:wrap;}.m2-logo img{max-height:52px;max-width:190px;object-fit:contain;}.m2-kicker{font-size:9px;font-weight:800;letter-spacing:0.25em;color:#64748b;margin-top:8px;}.m2-right{text-align:right;max-width:420px;}.m2-title{font-size:18px;font-weight:800;color:#1d4ed8;letter-spacing:-0.02em;line-height:1.2;}.m2-sub{font-size:10px;color:#64748b;margin-top:6px;font-weight:500;}.m2-date{font-size:10px;color:#94a3b8;margin-top:10px;}.body-wrap{padding:6px 4px 24px;}.sec{margin:16px 0;padding:17px 20px;background:#fff;border-radius:10px;border-left:4px solid #3b82f6;box-shadow:0 1px 3px rgba(0,0,0,0.05);}.sec-title{margin:0 0 12px;color:#1e40af;font-size:10.5px;font-weight:800;text-transform:uppercase;letter-spacing:0.08em;}.cl-table{width:100%;border-collapse:collapse;}.cl-table .cl-label{width:30%;padding:8px 10px 8px 0;font-weight:700;color:#475569;font-size:9.5px;text-transform:uppercase;}.cl-table .cl-value{color:#0f172a;}.texto-inicial{white-space:pre-wrap;margin:0;color:#334155;}.footer-bar{margin-top:24px;padding-top:14px;border-top:1px solid #e2e8f0;display:flex;justify-content:space-between;flex-wrap:wrap;gap:10px;}.footer-date{font-size:10px;color:#64748b;}.doc-ref{font-size:8.5px;color:#94a3b8;font-family:Consolas,monospace;}`,
    PRINT_SAFE +
      `body{font-family:'Segoe UI',system-ui,sans-serif;margin:0;padding:0;color:#1e293b;font-size:11.5pt;background:#f1f5f9;}.pdf-header.m3{background:#0f172a;color:#f8fafc;position:relative;}.m3-bar{height:5px;background:linear-gradient(90deg,#ea580c,#fb923c,#ea580c);}.m3-inner{display:flex;justify-content:space-between;align-items:center;padding:20px 26px;gap:20px;flex-wrap:wrap;}.m3-left img{max-height:48px;max-width:170px;display:block;}.m3-brand{font-size:11px;font-weight:800;color:#fb923c;margin-top:8px;letter-spacing:0.05em;}.m3-right{text-align:right;}.m3-title{font-size:16px;font-weight:700;color:#fff;}.m3-date{font-size:10px;color:#94a3b8;margin-top:8px;}.body-wrap{padding:4px 0 24px;}.sec{margin:16px 0;padding:18px;background:#fff;border-radius:10px;border:1px solid #cbd5e1;box-shadow:0 2px 6px rgba(0,0,0,0.04);}.sec-title{margin:0 0 11px;color:#c2410c;font-size:10.5px;font-weight:800;text-transform:uppercase;letter-spacing:0.07em;}.cl-table .cl-label{color:#64748b;width:28%;font-weight:700;font-size:9.5px;text-transform:uppercase;}.cl-table .cl-value{color:#0f172a;}.texto-inicial{white-space:pre-wrap;margin:0;}.footer-bar{margin-top:22px;padding-top:14px;border-top:1px solid #cbd5e1;display:flex;justify-content:space-between;flex-wrap:wrap;}.footer-date{font-size:10px;color:#64748b;}.doc-ref{font-size:8.5px;color:#94a3b8;font-family:Consolas,monospace;}`,
    PRINT_SAFE +
      `body{font-family:'Segoe UI',system-ui,sans-serif;margin:0;padding:0;color:#134e4a;font-size:11.5pt;background:#ecfeff;}.pdf-header.m4{background:linear-gradient(145deg,#0f766e 0%,#115e59 55%,#134e4a 100%);color:#fff;padding:0;}.m4-accent{height:5px;background:linear-gradient(90deg,#5eead4,#2dd4bf,#14b8a6);}.m4-inner{display:flex;align-items:center;justify-content:space-between;padding:22px 28px;gap:20px;flex-wrap:wrap;}.m4-logo img{max-height:54px;max-width:200px;object-fit:contain;}.logo-fallback{color:#ccfbf1;font-size:20px;font-weight:800;}.m4-text{text-align:right;}.m4-company{font-size:11px;font-weight:800;letter-spacing:0.15em;opacity:0.85;}.m4-doc{font-size:16px;font-weight:700;margin-top:6px;}.m4-date{font-size:10px;opacity:0.8;margin-top:10px;}.body-wrap{padding:6px 2px 24px;}.sec{margin:16px 0;padding:19px 22px;background:#fff;border-radius:14px;border:1px solid #99f6e4;box-shadow:0 4px 20px rgba(13,148,136,0.12);}.sec-title{margin:0 0 12px;color:#0f766e;font-size:10.5px;font-weight:800;text-transform:uppercase;letter-spacing:0.1em;}.cl-table .cl-label{color:#0d9488;font-weight:800;width:30%;font-size:9.5px;}.cl-table .cl-value{color:#134e4a;}.texto-inicial{white-space:pre-wrap;margin:0;}.footer-bar{margin-top:24px;padding-top:14px;border-top:1px solid #99f6e4;display:flex;justify-content:space-between;flex-wrap:wrap;}.footer-date{font-size:10px;color:#0d9488;}.doc-ref{font-size:8.5px;color:#64748b;font-family:Consolas,monospace;}`,
    PRINT_SAFE +
      `body{font-family:ui-monospace,'Cascadia Code',Consolas,monospace;margin:0;padding:0;color:#111827;font-size:10.5pt;background:#f9fafb;line-height:1.5;}.pdf-header.m5{background:#1f2937;color:#e5e7eb;border:2px solid #374151;}.m5-strip{background:#111827;padding:10px 16px;font-size:9px;letter-spacing:0.12em;text-align:center;color:#9ca3af;font-weight:700;}.m5-body{display:flex;justify-content:space-between;align-items:center;padding:16px 20px;gap:16px;flex-wrap:wrap;}.m5-logo img{max-height:42px;max-width:160px;vertical-align:middle;}.m5-fallback{font-weight:800;font-size:14px;color:#fff;}.m5-meta{font-size:10px;color:#d1d5db;line-height:1.45;max-width:55%;text-align:right;}.m5-d{color:#9ca3af;}.body-wrap{padding:4px 0 20px;}.sec{margin:14px 0;padding:14px 16px;background:#fff;border:1px dashed #6b7280;border-radius:3px;}.sec-title{margin:0 0 8px;color:#111827;font-size:10px;font-weight:800;text-transform:uppercase;border-bottom:1px dashed #9ca3af;padding-bottom:8px;letter-spacing:0.06em;}.cl-table .cl-label{width:32%;font-weight:800;color:#4b5563;font-size:9px;text-transform:uppercase;}.cl-table .cl-value{color:#111827;}.texto-inicial{white-space:pre-wrap;margin:0;}.footer-bar{margin-top:20px;padding-top:12px;border-top:1px dashed #6b7280;display:flex;justify-content:space-between;flex-wrap:wrap;}.footer-date{font-size:9px;color:#6b7280;}.doc-ref{font-size:8px;color:#9ca3af;}`,
    PRINT_SAFE +
      `body{font-family:Georgia,'Times New Roman',serif;margin:0;padding:0;color:#422006;font-size:11.5pt;background:#fff;}.pdf-header.m6{border-bottom:6px solid #7f1d1d;}.m6-gold{height:4px;background:linear-gradient(90deg,#a16207,#facc15,#a16207);}.m6-inner{padding:24px 30px 20px;}.m6-title{font-size:26px;font-weight:700;color:#7f1d1d;letter-spacing:0.03em;}.m6-sub{font-size:15px;color:#78350f;margin-top:8px;font-style:italic;font-weight:500;}.m6-row{display:flex;justify-content:space-between;align-items:flex-end;margin-top:16px;flex-wrap:wrap;gap:12px;}.m6-logo img{max-height:48px;max-width:170px;}.m6-date{font-size:10px;color:#92400e;}.body-wrap{padding:4px 0 24px;}.sec{margin:18px 0;padding:17px 20px;background:#fffbf5;border:1px solid #e7d5c4;border-radius:3px;}.sec-title{margin:0 0 10px;color:#7f1d1d;font-size:10.5px;font-weight:800;text-transform:uppercase;border-left:4px solid #ca8a04;padding-left:12px;letter-spacing:0.06em;}.cl-table .cl-label{width:30%;color:#78350f;font-weight:700;font-size:10px;}.cl-table .cl-value{font-family:Georgia,serif;color:#422006;}.texto-inicial{white-space:pre-wrap;margin:0;font-family:Georgia,serif!important;line-height:1.55;}.footer-bar{margin-top:22px;padding-top:14px;border-top:1px solid #e7d5c4;display:flex;justify-content:space-between;flex-wrap:wrap;}.footer-date{font-size:10px;color:#92400e;}.doc-ref{font-size:8.5px;color:#a8a29e;font-family:Georgia,serif;}`,
    PRINT_SAFE +
      `body{font-family:'Segoe UI',system-ui,sans-serif;margin:0;padding:0;color:#334155;font-size:11.5pt;background:#f1f5f9;}.pdf-header.m7{background:#1e293b;color:#f8fafc;padding:0;}.m7-inner{display:flex;align-items:flex-start;gap:28px;padding:26px 30px;flex-wrap:wrap;}.m7-logo img{max-height:56px;max-width:200px;object-fit:contain;}.m7-main{flex:1;min-width:200px;}.m7-brand{font-size:10px;font-weight:800;letter-spacing:0.2em;color:#94a3b8;margin-bottom:8px;}.m7-doc{margin:0;font-size:20px;font-weight:800;color:#fff;letter-spacing:-0.02em;line-height:1.25;}.m7-foot{margin-top:12px;font-size:10px;color:#94a3b8;}.body-wrap{padding:6px 0 26px;}.sec{margin:16px 0;padding:18px 22px;background:#fff;border-radius:10px;border:1px solid #e2e8f0;box-shadow:0 1px 3px rgba(0,0,0,0.06);}.sec-title{margin:0 0 12px;font-size:10px;font-weight:800;letter-spacing:0.1em;color:#475569;text-transform:uppercase;border-bottom:2px solid #e2e8f0;padding-bottom:10px;}.cl-table{width:100%;border-collapse:collapse;}.cl-table tr{border-bottom:1px solid #f1f5f9;}.cl-table .cl-label{width:32%;padding:9px 12px 9px 0;font-weight:700;color:#64748b;font-size:9.5px;text-transform:uppercase;}.cl-table .cl-value{color:#0f172a;}.texto-inicial{white-space:pre-wrap;margin:0;line-height:1.55;}.footer-bar{margin-top:24px;padding-top:14px;border-top:1px solid #cbd5e1;display:flex;justify-content:space-between;flex-wrap:wrap;}.footer-date{font-size:10px;color:#64748b;}.doc-ref{font-size:8.5px;color:#94a3b8;font-family:Consolas,monospace;}`,
    PRINT_SAFE +
      `body{font-family:'Segoe UI',system-ui,sans-serif;margin:0;padding:0;color:#0f172a;font-size:11.5pt;background:#fff;}.pdf-header.m8{padding:20px;}.m8-frame{border:3px double #1e293b;padding:24px 28px;border-radius:2px;background:#fff;}.m8-logo{text-align:center;margin-bottom:16px;}.m8-logo img{max-height:52px;max-width:200px;object-fit:contain;}.m8-center{text-align:center;}.m8-name{font-size:11px;font-weight:800;letter-spacing:0.35em;color:#64748b;margin-bottom:10px;}.m8-doc{font-size:18px;font-weight:800;color:#0f172a;margin-bottom:8px;}.m8-date{font-size:10px;color:#64748b;}.body-wrap{padding:8px 4px 28px;}.sec{margin:16px 0;padding:18px 22px;border:1px solid #cbd5e1;border-radius:4px;background:#fafafa;}.sec-title{margin:0 0 12px;font-size:10px;font-weight:800;text-transform:uppercase;letter-spacing:0.1em;color:#334155;border-bottom:1px solid #94a3b8;padding-bottom:8px;}.cl-table .cl-label{width:32%;font-weight:700;font-size:9.5px;color:#475569;text-transform:uppercase;}.cl-table .cl-value{color:#0f172a;}.texto-inicial{white-space:pre-wrap;margin:0;}.footer-bar{margin-top:24px;padding-top:14px;border-top:2px double #cbd5e1;display:flex;justify-content:space-between;flex-wrap:wrap;}.footer-date{font-size:10px;color:#64748b;}.doc-ref{font-size:8.5px;color:#94a3b8;font-family:Consolas,monospace;}`,
    PRINT_SAFE +
      `body{font-family:'Segoe UI',system-ui,sans-serif;margin:0;padding:0;color:#1e3a5f;font-size:11.5pt;background:linear-gradient(180deg,#eff6ff 0%,#fff 120px);}.pdf-header.m9{background:#fff;padding:0;border-bottom:3px solid #2563eb;}.m9-inner{padding:22px 28px;display:flex;align-items:center;gap:24px;flex-wrap:wrap;}.m9-badge{width:6px;align-self:stretch;background:linear-gradient(180deg,#3b82f6,#1d4ed8);border-radius:3px;min-height:72px;}.m9-content{display:flex;align-items:center;gap:22px;flex:1;flex-wrap:wrap;}.m9-logo img{max-height:50px;max-width:180px;}.m9-brand{font-size:10px;font-weight:800;color:#3b82f6;letter-spacing:0.12em;text-transform:uppercase;}.m9-title{font-size:17px;font-weight:800;color:#1e3a8a;margin-top:4px;line-height:1.3;}.m9-date{font-size:10px;color:#64748b;margin-top:8px;}.body-wrap{padding:6px 0 24px;}.sec{margin:16px 0;padding:18px 20px;background:#fff;border-radius:12px;border:1px solid #bfdbfe;box-shadow:0 2px 8px rgba(37,99,235,0.06);}.sec-title{margin:0 0 12px;color:#1d4ed8;font-size:10.5px;font-weight:800;text-transform:uppercase;letter-spacing:0.08em;}.cl-table .cl-label{color:#3b82f6;font-weight:700;width:30%;font-size:9.5px;text-transform:uppercase;}.cl-table .cl-value{color:#1e293b;}.texto-inicial{white-space:pre-wrap;margin:0;line-height:1.55;}.footer-bar{margin-top:22px;padding-top:14px;border-top:1px solid #bfdbfe;display:flex;justify-content:space-between;flex-wrap:wrap;}.footer-date{font-size:10px;color:#64748b;}.doc-ref{font-size:8.5px;color:#94a3b8;font-family:Consolas,monospace;}`,
    PRINT_SAFE +
      `body{font-family:'Segoe UI',system-ui,sans-serif;margin:0;padding:0;color:#fafafa;font-size:11.5pt;background:#18181b;}.pdf-header.m10{background:linear-gradient(180deg,#09090b 0%,#18181b 100%);color:#fafafa;padding:0;border-bottom:3px solid #d4af37;}.m10-gold{height:3px;background:linear-gradient(90deg,#854d0e,#facc15,#854d0e);}.m10-inner{display:flex;justify-content:space-between;align-items:center;padding:22px 28px;gap:20px;flex-wrap:wrap;}.m10-left img{max-height:52px;max-width:190px;object-fit:contain;}.m10-right{text-align:right;}.m10-k{font-size:9px;font-weight:800;letter-spacing:0.25em;color:#a1a1aa;}.m10-t{font-size:17px;font-weight:800;color:#fff;margin-top:8px;line-height:1.25;}.m10-d{font-size:10px;color:#a1a1aa;margin-top:10px;}.body-wrap{padding:8px 4px 26px;color:#e4e4e7;background:#fafafa;border-radius:0;}.body-wrap .sec{color:#18181b;background:#fff;border:1px solid #e4e4e7;}.body-wrap .sec-title{color:#18181b;border-bottom-color:#d4d4d8;}.body-wrap .cl-table .cl-label{color:#52525b;}.body-wrap .cl-table .cl-value{color:#18181b;}.body-wrap .texto-inicial{color:#27272a;}.sec{margin:16px 0;padding:18px 22px;border-radius:12px;}.sec-title{margin:0 0 12px;font-size:10.5px;font-weight:800;text-transform:uppercase;letter-spacing:0.08em;padding-bottom:10px;border-bottom:2px solid #e4e4e7;}.cl-table{width:100%;border-collapse:collapse;}.cl-table tr{border-bottom:1px solid #f4f4f5;}.cl-table .cl-label{width:32%;padding:9px 12px 9px 0;font-weight:700;font-size:9.5px;text-transform:uppercase;}.texto-inicial{white-space:pre-wrap;margin:0;line-height:1.55;}.footer-bar{margin-top:24px;padding-top:14px;border-top:1px solid #d4d4d8;display:flex;justify-content:space-between;flex-wrap:wrap;}.footer-date{font-size:10px;color:#52525b;}.doc-ref{font-size:8.5px;color:#71717a;font-family:Consolas,monospace;}`,
    PRINT_SAFE +
      `body{font-family:'Segoe UI',system-ui,sans-serif;margin:0;padding:0;color:#312e81;font-size:11.5pt;background:#fafafa;}.pdf-header.m11{display:flex;background:#fff;min-height:100px;border-bottom:1px solid #e0e7ff;}.m11-stripe{width:10px;background:linear-gradient(180deg,#4f46e5,#6366f1,#4f46e5);flex-shrink:0;}.m11-inner{flex:1;display:flex;align-items:center;justify-content:space-between;padding:20px 26px;gap:20px;flex-wrap:wrap;}.m11-logo img{max-height:50px;max-width:185px;object-fit:contain;}.m11-text{text-align:right;}.m11-b{font-size:9px;font-weight:800;letter-spacing:0.2em;color:#6366f1;text-transform:uppercase;}.m11-d{font-size:17px;font-weight:800;color:#312e81;margin-top:6px;line-height:1.25;}.m11-meta{font-size:10px;color:#64748b;margin-top:10px;}.body-wrap{padding:6px 0 26px;}.sec{margin:16px 0;padding:18px 22px;background:#fff;border-radius:12px;border:1px solid #e0e7ff;box-shadow:0 2px 8px rgba(79,70,229,0.07);}.sec-title{margin:0 0 12px;color:#4338ca;font-size:10.5px;font-weight:800;text-transform:uppercase;letter-spacing:0.09em;border-bottom:2px solid #e0e7ff;padding-bottom:10px;}.cl-table .cl-label{width:31%;font-weight:800;color:#6366f1;font-size:9.5px;text-transform:uppercase;}.cl-table .cl-value{color:#1e1b4b;}.texto-inicial{white-space:pre-wrap;margin:0;line-height:1.55;}.footer-bar{margin-top:24px;padding-top:14px;border-top:1px solid #c7d2fe;display:flex;justify-content:space-between;flex-wrap:wrap;}.footer-date{font-size:10px;color:#64748b;}.doc-ref{font-size:8.5px;color:#94a3b8;font-family:Consolas,monospace;}`,
    PRINT_SAFE +
      `body{font-family:'Segoe UI',system-ui,sans-serif;margin:0;padding:0;color:#111827;font-size:11pt;background:#fff;}.pdf-header.m12{border:1px solid #d1d5db;}.m12-top{background:#374151;color:#f9fafb;font-size:9px;font-weight:800;letter-spacing:0.14em;text-align:center;padding:10px 16px;text-transform:uppercase;}.m12-mid{display:flex;justify-content:space-between;align-items:center;padding:14px 20px;gap:16px;flex-wrap:wrap;border-bottom:2px solid #111827;}.m12-logo img{max-height:44px;max-width:170px;vertical-align:middle;}.m12-info{font-size:10px;color:#374151;line-height:1.5;max-width:58%;text-align:right;}.m12-rule{height:4px;background:repeating-linear-gradient(90deg,#111827 0px,#111827 8px,transparent 8px,transparent 14px);}.body-wrap{padding:8px 4px 24px;}.sec{margin:14px 0;padding:16px 18px;background:#f9fafb;border:1px solid #e5e7eb;border-left:4px solid #111827;}.sec-title{margin:0 0 10px;font-size:10px;font-weight:800;text-transform:uppercase;letter-spacing:0.1em;color:#111827;border-bottom:1px solid #d1d5db;padding-bottom:8px;}.cl-table{font-size:10.5pt;}.cl-table .cl-label{width:30%;font-weight:800;color:#4b5563;font-size:9px;text-transform:uppercase;font-family:ui-monospace,monospace;}.cl-table .cl-value{color:#111827;font-family:ui-monospace,monospace;}.texto-inicial{white-space:pre-wrap;margin:0;line-height:1.5;font-family:ui-monospace,monospace;font-size:10.5pt;}.footer-bar{margin-top:20px;padding-top:12px;border-top:2px solid #111827;display:flex;justify-content:space-between;flex-wrap:wrap;}.footer-date{font-size:9px;color:#6b7280;font-family:ui-monospace,monospace;}.doc-ref{font-size:8px;color:#9ca3af;font-family:ui-monospace,monospace;}`,
  ]
}

let _cssCache: string[] | null = null
function getCssBlocks(): string[] {
  if (!_cssCache) _cssCache = cssBlocks()
  return _cssCache
}

/**
 * Monta o HTML completo para janela de impressão (PDF).
 * @param idx0 índice 0–11 (modelo PDF − 1)
 */
export function buildProtocoloServicoPrintHtml(
  idx0: number,
  headerOpts: HeaderOpts,
  bodyInner: string
): string {
  const idx = Math.max(0, Math.min(11, idx0))
  const css = getCssBlocks()[idx]
  const header = buildHeaderFragments(headerOpts)[idx]
  const titleSafe = headerOpts.tituloProto.replace(/</g, '&lt;').replace(/>/g, '&gt;')
  return `<!DOCTYPE html><html lang="pt"><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width, initial-scale=1"/><title>${titleSafe}</title><style>${css}</style></head><body>${header}<div class="body-wrap">${bodyInner}</div></body></html>`
}
